Merged in HERMES-98-icebridge-script (pull request #94)
HERMES-98 icebridge script

* allow the python script to take a URL list instead of normal params

* update MIME type of script from "text" to "application"

* expose the content-disposition header to appease CORS

    slack discussion link - https://nsidc.slack.com/archives/C4UCJ1NAF/p1570745606013800

    More to the point, github issue link - https://github.com/matthew-andrews/isomorphic-fetch/issues/67

* var name

* upgrade mypy-stubs

* quiet mypy

    It appears an update to typeshed broke this line. Error message:

    tasks.py:9:44: error: Argument 1 to "getfile" has incompatible type
    "Optional[FrameType]"; expected "Union[Module, Type[Any], MethodType,
    FunctionType, TracebackType, FrameType, CodeType, Callable[..., Any]]"

* use pprint to format the url list in the python script for better readability

    [ci skip]

Approved-by: Michael Brandt <michael.brandt@nsidc.org>